language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dmitry-gorbar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dmitry-gorbar/docker-react npm run test