FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]



#docker build -f Dockerfile.dev -t front .
#docker run -it -p 3000:3000 -v /app/node_modules -v /d/work/projects/education/docker/frontend:/app -e CHOKIDAR_USEPO LLING=true front 